apiVersion: v1
kind: Secret
metadata:
  name: flower-credentials
type: Opaque
stringData:
  flower.user: {{ .Values.secrets.flower.user }}
  flower.password: {{ .Values.secrets.flower.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  backend.secret_key: {{ .Values.secrets.secret_key }}
  backend.gitlab_token: {{ .Values.secrets.gitlab_token }}
  backend.social_auth_gitlab_key: {{ .Values.secrets.social_auth_gitlab_key }}
  backend.social_auth_gitlab_secret: {{ .Values.secrets.social_auth_gitlab_secret }}
  backend.slack.token: {{ .Values.secrets.slack.token }}
  backend.email.user: {{ .Values.secrets.email.user }}
  backend.email.password: {{ .Values.secrets.email.password }}
  backend.sentry.dsn: {{ .Values.secrets.sentry.dsn }}
